### ISSUE TITLE
Hide "Nothing selected" option?

### ISSUE THREAD

**Issue by johnnyshields** [sukima/ember-cli-select-picker#23]
How do I remove this "Nothing selected"? In my case, I want the first option in the dropdown to be the default (I'm using single-select mode)

**Comment by sukima** [comment]
I hadn't thought of this case damn. :confounded: 

I'm swamped these few weeks pushing a big project which doesn't use this feature at this time. I have to defer till later or beg for a pull request.

Sorry about that.

**Comment by johnnyshields** [comment]
I can stay using version 1.2.0 for now but would like to have this soon.

Similar plugins I've seen have an input variable "prompt=xxx" or "includeBlank=xxx". It's pretty essential for any select picker type plugin.

**Comment by sukima** [comment]
So I was mulling over this while on the train. I need your help. Instead of a possible solution I was struck with a bit of confusion on what this actually should be. Let me explain.

The native picker (which lies as a view hidden by the template and is only visible on small screens) has this concept of a prompt. This prompt is only used on single pickers and injects an option to the top of the list. I assume (though I don't actually know) that the Ember view is clever enough to _ignore_ that option. I'm not entirely confident about how this works. There also seems to be some disparity in the relationship between the `value` and the `selection`. In fact I've found that `selection` lives a double life and can be any of the following: null, Empty array, array of choices, and just the value (not an array).

Add on the complication in that the markup for the bootstrap version has it's own concept of the main button text (`summaryMessage`) which could take over the very concept of a prompt anyway.

So now I'm left with does the prompt become a choice you can go back to? How is it handed in multiple selections? Is it just a summary and not part of the list?

Can you help me spec out what this feature should look like for both single and multiple pickers and what it should not do? Thanks.

**Comment by johnnyshields** [comment]
@sukima I think we can ignore this option for multiple pickers, it's only relevant for single pickers (but is very important for them.)

**Comment by sukima** [comment]
This seems to be affecting our app and a a ticket has been filed to look into it. Maybe it will gain some head way sooner then later.

**Comment by johnnyshields** [comment]
OK cool. Thanks. I'll stay version locked at 1.2.0 for now.

**Comment by sukima** [comment]
@johnnyshields So we looked into this and least on our side things were working as expected. One thing we had to do was add `nothingSelectedMessage`. Can you try that and see if it works.

The reasoning is because of commit 0f152663102959ce05897247442ddff7d741b6e7 which attempted to separate the native select view's `prompt` logic and the select-picker component's `summaryMessage` logic. It wasn't a perfect solution.

In your case I would guess try removing prompt and it should select the first choice by default. Another option is to use `nothingSelectedMessage` for the bootstrap prompt and `prompt` for the _native_ select component under the hood.

Let me know if this helps. If not I'll take another look at it. For reference here is [the part of the code](https://github.com/sukima/ember-cli-select-picker/blob/master/addon/mixins/select-picker.js#L191-L222) that manages that message.

**Comment by johnnyshields** [comment]
@sukima I'll take a look in the future, as it is I have version 1.2.0 in production and don't have a strong reason to upgrade at the moment. I don't use native so it sounds like your solution will probably work. When I need to upgrade I'll take a look.

It might be nice to add a few tests for this in the meantime, it surprised us in our dev env when version was auto-upgraded by npm.

**Comment by sukima** [comment]
Yeah I bumped the second number instead of the patch number because it was an API change. `~x.x.x` would have prevented an update while `^x.x.x` would trigger an update.

Sorry for the confusion. Let me know if 1.4.0 and the above options fix your trouble because there were a few good bug fixes between 1.2.0 and 1.4.0.

**Comment by sukima** [comment]
Closing due to atrophy. Reopen if needed.
