### ISSUE TITLE
Is this plugin compatible with Ember 2.0?

### ISSUE THREAD

**Issue by chrissvo** [sukima/ember-cli-select-picker#34]
I'm getting this build error: `Assertion Failed: Using`{{view}}`or any path based on it ('admin/templates/components/list-picker.hbs' @ L1:C0) has been removed in Ember 2.0`

**Comment by sukima** [comment]
Not yet.

**Comment by fizz** [comment]
I'm using it with canary, it seems to work fine...

**Comment by sukima** [comment]
@fizz Thanks, that is good to know. I was a bit worried on what to do with 2.0.

Speaking of which, it would help things if I knew which version of the select-picker addon each of you is using.

**Comment by fizz** [comment]
@sukima I'm using 2.2.0

**Comment by chrissvo** [comment]
I'm currently using the ember default

**Comment by fizz** [comment]
@Chrissvo, I just reread your first comment and understood what's going on. I think your issue is solved by https://github.com/sukima/ember-cli-select-picker/commit/8c0cdb36813a1ead1017326e8280da9ce8857e17 so you might want to upgrade your version in package.json. 

If you just `ember install ember-cli-select-picker` it'll upgrade you to 2.2.0 and the add-on will no longer be using a view.

**Comment by fizz** [comment]
Either that or use `nativeMobile=false` to skip the select view.

**Comment by chrissvo** [comment]
Thanks @fizz, just tested this and it works! Closing the issue
